### ISSUE TITLE
Bad contrast for some heuristic provided images

### ISSUE THREAD

**Issue by wischi-chr** [helloworld1/FreeOTPPlus#94] opened 2020-09-25 01:06 UTC
For example the GitHub icon is black and doesn't look good an dark more. May provide different images for light and dark mode?

**Comment by helloworld1** [comment] 2020-09-25 05:35
Thanks for reporting. I am aware of the issue. I plan to use a gray background for the icons in dark mode.

**Comment by helloworld1** [comment] 2020-10-31 21:42
The issue is fixed in this commit https://github.com/helloworld1/FreeOTPPlus/commit/1d5c0fb0f5e4791d653fbee0f1935da216ffa217

**Closed by helloworld1** 2020-10-31 21:42 UTC
