### ISSUE TITLE
Manual rearranging suddenly behaves differently? Exchanges items!

### ISSUE THREAD

**Issue by ralfbergs** [helloworld1/FreeOTPPlus#185] opened 2022-02-18 15:53 UTC
I suddenly see a very annoying behavior that WILL make me abandon this tool I loved so much soon, if not fixed... :-(

When I want to rearrange entries, I used to "tap" and keep-tapped an entry, then move to some other place where I wanted to insert this entry, and then release the entry.

Unfortunately, this no longer works that way. It seems that wherever I drag something, the item at the new place and the original item exchange their positions... ;-(

To elaborate, let's say we have the following:

`R-A-C-S-T-Z`

I want to drag "R" to the proper place so that everything is alphabetically sorted again.

I drag "R" to the place between "C" and "S". "R" will then be at the proper place, but "C" or "S" will suddenly be at the first position. :-(

Like this:

`C-A-R-S-T-Z`

I'm using this fine tool since years, but I've never seen such a weird behavior before... ;-(

Any idea, please?

**Comment by helloworld1** [comment] 2022-03-04 22:36
Yes, it is a behavior change in the list handling (By using more modern libraries). It is definitely not as smooth.

**Comment by helloworld1** [comment] 2022-03-04 22:37
Will keep this bug open until we have a fix.

**Comment by error401de** [comment] 2022-04-25 07:46
Just wanted to ask if there is an ETA for this. Unfortunately this issue is really incredible intrusive, basically I am completely unable to sort (new) items any.

**Comment by helloworld1** [comment] 2022-04-25 22:01
Unfortunately no ETA and definitely not in the 2.8 release since it is an easy fix. The current Google gesture library has this janky experience. I may need to use an alternative way to implement.
The technical part for the issue is that when the items are being moved, I don't want the library to commit the change until the item is settled. But the current way is that when the item moved, it triggers a change commit resulting in the item saved and notifying UI refresh. I hate this behavior and found no easy workaround.

**Comment by bmoneke** [comment] 2022-06-01 21:07
Thanks for keeping an eye on this.

**Comment by JasonRaveling** [comment] 2022-07-12 16:43
Talk about timing. I have been wanting to open an issue for this and finally came to do it. The fix (hopefully!) is fixed in a pull request about 25 min ago :-)

Thanks for making this available and for your continued work on it :-)

**Closed** 2022-07-15 16:16 UTC

**Comment by ralfbergs** [comment] 2022-10-01 08:56
Until a release is published in Google Play that has the above mentioned fix included, I'm using the below work-around on the JSON export to sort the entries alphabetically (in a case-**in**sensitive manner):
`cat freeotp-backup.json|jq '.tokenOrder|=sort_by(. | ascii_downcase)' >freeotp_sorted.json`
