### ISSUE TITLE
[ Feature Request ] Use current labels / issuer on export

### ISSUE THREAD

**Issue by james-reed** [helloworld1/FreeOTPPlus#72] opened 2020-02-15 08:24 UTC
Hi.

I've noticed when performing an export in either available format, the exported files contain the original labels and issuer from when QR codes were originally scanned, rather than the details you've currently got set if you edited the labels.

Is this intentional? If you've made edits it means when you export and then import if you're moving to a new device for example, any edits you've made are lost.

Thanks.

**Comment by helloworld1** [comment] 2020-02-16 05:04
That should not be intentional. It could be an issue of how original FreeOTP saves the token. It may keep a separate copy of original label / issuer and modified ones. I think we should save the modified ones if it is.

Could you try to export as uri file format and see if it has the same issue?

**Comment by james-reed** [comment] 2020-02-16 22:52
I can confirm that the issue is present on either URI type export or JSON type.

**Comment by helloworld1** [comment] 2021-06-11 05:30
The issue is fixed in the https://github.com/helloworld1/FreeOTPPlus/commit/cb35197463270f8f784c5f7b41f80fd088d233f3
The exported issuer / label will be the current modified instead of the original.

**Closed by helloworld1** 2021-06-11 05:30 UTC
