### ISSUE TITLE
App shows only 4 digits of a 6 digit code

### ISSUE THREAD

**Issue by GHPS** [helloworld1/FreeOTPPlus#147] opened 2021-09-10 19:56 UTC
Problem: After scanning a 6 digit code only 4 digits are displayed.
The problem is caused by the two token per line grip layout - the
column is not wide enough for a 6 digit code.

Background: I was setting up the 2FA on Github with FreeOTPPlus but
couldn't  enter the required 6 digits since the app gave me only 4 digits.
First I tried padding the number with zeros which expectingly didn't work.
Tapping on the Github token showed that the app correctly found a 6 digit token. 

Quick fix: As a last resort to display the missing 2 digits I rotated the
device from portrait to landscape orientation. And voila, 6 instead of 4
digits were displayed.

Platform: FreeOTPPlus 2.4 (15), Android 9 on Samsung Note 8 (SM-N950F)
with latest updates installed.

**Comment by helloworld1** [comment] 2021-09-10 23:49
Thank you for the report. I cannot reproduce the issue on my emulator or on galaxy  s20. Could you share a screenshot to illustrate the issue?

**Comment by GHPS** [comment] 2021-09-12 15:42
Included you'll find the two screenshots. Excuse the quality - since the
security settings of Android 9 prevent screenshotting FreeOTP, these
are real screenshots from  a second phone.

While taking the shots I've come across another problem: The app invalidates
the current code when the phone is rotated from portrait to landscape
(or back).

![FreeOTP4Digit](https://user-images.githubusercontent.com/1478398/132993810-ea76523c-a37b-4898-b397-6cebea56e6a0.jpg)
![FreeOTP6Digit](https://user-images.githubusercontent.com/1478398/132993817-b1c47c2d-63dc-4e1e-90fb-3d92be999d8f.jpg)

**Comment by helloworld1** [comment] 2021-09-12 16:16
Thanks for the detailed report. I know the issue now. Galaxy note 8 has 414dp width but new freeotp is treating 400+ dp as tablet and is displaying two columns. I will fix the issue asap by using 480dp width instead.

**Comment by GHPS** [comment] 2021-09-12 17:25
Great - thanks for your work.

Another approach would be to split the screen horizontally in two parts: 
- A top message area which shows the 6 digits, clock and the provider.
- A lower part with icons in rows of two to select from.

Other apps use this layout and it is quite elegant.

**Comment by helloworld1** [comment] 2021-09-17 18:14
The issue is fixed with
https://github.com/helloworld1/FreeOTPPlus/commit/59c124fe1ca7cdfbed36bbc1661c6a70b9c851bb

**Closed by helloworld1** 2021-09-17 18:14 UTC

**Comment by helloworld1** [comment] 2021-09-18 22:57
2.5 was released to fix the issue.

**Comment by GHPS** [comment] 2021-09-22 13:45
Great - I've just checked and the problem is indeed fixed.

The second issue, however, is still there - the token displayed
gets invalidated when the device is rotated.
