### ISSUE TITLE
OTP Codes Truncated on Larger Screen

### ISSUE THREAD

**Issue by tiernan** [helloworld1/FreeOTPPlus#151] opened 2021-09-19 13:53 UTC
I just switched from a Pixel 4a to 5a. On the new phone the UI displays OTP accounts in a 2 column format that only shows the first 4 digits of the code generated as opposed to a single column displaying full codes on the previous device.

There is no way to see the full code now without rotating the screen to lanscape first, which is rather inconvenient. I imagine this is unintended behavior.

P. S. Thanks for the great app. I've used it for years and on many different devices now.

**Comment by arwarw** [comment] 2021-09-19 15:11
Can confirm: Since the F-Droid update from 2.3 to 2.4, the two-column layout truncates all 6-digit or longer codes to 5 digits, without an obvious or easy way to see all the code (or even see, that a part of the code is missing). My phone is an FxTec Pro1 with a 1080x2160px screen.

Easiest workaround is to rotate to landscape format, the three-column layout seems to have sufficient space for at least 6 (maybe even 8) digits per code.

**Comment by tiernan** [comment] 2021-09-19 15:30
I'd like to add the resolutions of my devices.
The 4a is 1080x2340 in a 5.8in screen;.
The 5a is 1080x2400 in 6.4in.

This probably puts the 5a in a different density bucket.

**Comment by Krzmbrzl** [comment] 2021-09-19 17:33
Same issue on a Shiftphone 6m. In portrait orientation I only see four digits of the generated code whereas in landscape mode I see the full six digits.

For me this also started happening with 2.4 (most recent F-Droid update)

**Comment by helloworld1** [comment] 2021-09-19 17:53
Thanks for reporting this issue. The issue is fixed in the 2.5 release as an emergency release. I don't know when fdroid will pick up the chance.

**Comment by jugendhacker** [comment] 2021-09-19 20:54
F-Droid did pick it up pretty fast and even [build it successful already](https://monitor.f-droid.org/builds/log/org.liberty.android.freeotpplus/16), so now we are just waiting for the build cycle to end and then signing/deploy and 2.5 should land inside the store.

**Comment by pm-pm** [comment] 2021-09-21 12:43
WORKAROUND (works for me): **Use Landscape mode** to see all 6 Digits. ;-)

**Comment by Dmole** [comment] 2021-09-21 21:13
Same on Pixel 2.

Was this build even tested on a phone?

**Comment by helloworld1** [comment] 2021-09-21 21:44
Apologize for the issue. The build was tested on multiple versions of emulator and some recent Samsung and OnePlus phones. Unfortunate, the issue won't happen in the narrow phone with screen width less than 400 dp.  The issue was promptly fixed after being reported but needs time for fdroid to publish the new version.

**Comment by helloworld1** [comment] 2021-09-21 22:01
I noticed that the fastlane was not properly updated for the 2.5 release before branching. I wonder if it is causing the delays in F-Droid update. I updated this commit https://github.com/helloworld1/FreeOTPPlus/commit/38c2900b1f24b5d1e319d05c9eb2303ea8980bab and force pushed the branch RELEASE-2.5 and hope F-Droid will pick it up.

**Comment by Dmole** [comment] 2021-09-21 22:08
Thanks.

Just out of curiosity (and I may be reading the link wrong but) I think the Pixel 2 is 412 dp;
https://yesviz.com/devices/google-pixel2/

Exact threshold aside will a small (5") emulated device will be added to testing to avoid Density independent Pixel issues in the future?
Small devices are still in production;

https://www.gsmarena.com/results.php3?nYearMin=2021&fDisplayInchesMax=5&sAvailabilities=1&sFormFactors=1&sOSes=2

though maybe not for long;
2021 = 3
2020 = 12
2019 = 18
2018 = 49
2017 = 66

Emulator testing is likely fine but if you do want more on device testers,
putting beta builds a week before a stable version in the Releases part of GitHub is a good way to get them.

**Comment by helloworld1** [comment] 2021-09-21 22:17
The root cause of the issue is a miscalculation of the width and oversight of the testing. Version 2.4+ has added a bunch of automated integration tests to catch issues. If the test run on a pixel 2 device, it will surely fail. However, we don't have a service to test a combination of screen sizes and device versions.

In any case, for now, you can either wait for F-Droid update, compile your own version or use this pre-compiled debug version:
https://drive.google.com/file/d/1nfmZ7TZ4S2ERBlBOI3RXUCF8fn7QraGj/view?usp=sharing

The pre-compiled version is a separate app "FreeOTP+ Debug" so it won't overwrite the release app. The version is built on the master, slightly newer than the 2.5 release with an updated algorithm to calculate columns.

**Comment by helloworld1** [comment] 2021-09-21 22:22
Question for @jugendhacker, would the missing fastlane cause delayed F-Droid release? Should we just wait, or for me to author a new version with the correct fastlane changelog?

**Comment by jugendhacker** [comment] 2021-09-22 08:30
@helloworld1 no it should not delay anything, but maybe it did not pick up the fastlane metadata which should not be problematic. Looks like we just finished the build cycle and the app is currently getting signed, so it should arrive very soon in the repo.

**Comment by jugendhacker** [comment] 2021-09-22 09:37
It got deployed now and at least on my phone it fixed the issue.

**Comment by Krzmbrzl** [comment] 2021-09-22 09:42
I confirm that the update is now live on F-Droid and that it indeed fixes the issue. Now I have a single-column layout in portrait mode and a two-column layout in landscape mode where in each case the full 6 digits are displayed.

**Comment by meersjo** [comment] 2021-09-22 12:58
Also confirm that the update is live. I did have to manually refresh the repositories before it showed up.

**Comment by helloworld1** [comment] 2021-09-22 14:40
Thanks everyone!

**Closed by helloworld1** 2021-09-22 14:40 UTC
