### ISSUE TITLE
Custom icons do not persist

### ISSUE THREAD

**Issue by macravin** [helloworld1/FreeOTPPlus#8] opened 2018-04-12 19:20 UTC
If you set custom icons for the codes, they will not persist after exiting and relaunching the app.

Perhaps images should be copied into app data folder with built in content provider.

**Comment by helloworld1** [comment] 2018-04-12 19:36
Yea, confirmed the issue.

**Comment by silviuvulcan** [comment] 2018-11-26 05:59
But they are somehow kept - if I try to set it again the save option is grayed out and if I hit cancel the icon is restored - but still doesn't persist.

**Comment by SuperTux88** [comment] 2018-12-12 22:44
The original FreeOTP had the same bug, but there was a PR merged to fix it a year ago: https://github.com/freeotp/freeotp-android/pull/149, but there aren't any new releases. Maybe the same solution can be used here too?

**Comment by helloworld1** [comment] 2018-12-12 23:16
The patch obviously does not apply due to changes. But the principle in that PR applies.

**Comment by helloworld1** [comment] 2019-05-19 23:03
This issue is fixed in: 94418a4a5703abfab094d907e5cf2a4b12c388a0

**Closed by helloworld1** 2019-05-19 23:03 UTC
