### ISSUE TITLE
exits camera immediately when trying to scan QR code

### ISSUE THREAD

**Issue by KlavsKlavsen** [helloworld1/FreeOTPPlus#66] opened 2019-11-27 10:07 UTC
I tried with some barcodescanner app - and it stays in the camera without issues.
In FreeOTP it just shows the camera for a brief second - and then exits and goes back.. :(

Anything I can do to debug?

**Comment by KlavsKlavsen** [comment] 2019-11-27 10:08
I tried downgrading to 1.5 - but it just says it failed to downgrade due to "unknown error" :(

**Comment by vikingtiger** [comment] 2019-11-27 16:54
This seems to be duplicate of #60. @helloworld1 posted a link to a debug build there which appears to solve the problem.

**Comment by helloworld1** [comment] 2019-11-27 18:48
Close for duplicate #60 Thanks @vikingtiger  for mentioning

**Closed by helloworld1** 2019-11-27 18:48 UTC
