### ISSUE TITLE
F-Droid 3.1 version cannot be installed

### ISSUE THREAD

**Issue by Urbi2k** [helloworld1/FreeOTPPlus#262] opened 2024-02-02 23:46 UTC
I am using a stock Pixel 7 with Android 14. Since the release of Version 3.1 on F-Droid in December 23 I have tried to update my existing installation. However, it doesn't work: When I try to install the update I am asked if I want to install FreeOTP+ and if I click on install nothing happens. 
I just uninstalled FreeOTP+ hoping that I would be able to install it again. But that doesn't work. Neither through F-Droid nor by opening the APK I downloaded from F-Droid. 
However, the Google Play version works.

**Comment by vicnett** [comment] 2024-02-04 12:17
I have the exact same issue with my Pixel 8 Pro.

**Comment by helloworld1** [comment] 2024-02-10 18:15
I tested Samsung s21 with Android 14. It installs fine on FDroid. I wonder if it's pixel specific issues. Are you able to install other apps from F-Droid?

**Comment by Urbi2k** [comment] 2024-02-10 19:07
Yes. I have been using F-Droid for years without issues. Right now I have ~10 other apps from F-Droid. It might be Pixel related. No issues on my Galaxy TabActive3.

**Comment by helloworld1** [comment] 2024-02-10 19:17
Let me try to release a version with updated SDK version later to see if it resolves the build issue. Maybe it's some transient issue in F-Droid side.

**Comment by Urbi2k** [comment] 2024-02-10 19:25
Thank you.

**Comment by helloworld1** [comment] 2024-02-11 05:39
Released version 3.1.1 bumping AGP version. Hopefully F-Droid rebuilds and works fine now.

**Comment by nackd** [comment] 2024-02-15 12:15
Funnily, I had 3.1 installed from F-Droid and wasn't able to upgrade to 3.1.1. It's also a Pixel phone. I removed it and tried to install 3.1.1, 3.1 and 3.0 unsuccessfully, so I had to install from Play Store instead.

**Comment by vicnett** [comment] 2024-02-15 18:38
I still have the exact same issue with 3.1.1 unfortunately

**Comment by mmbannert** [comment] 2024-02-16 12:51
I could not update to 3.1.1 using F-Droid on my Pixel 6a. I tried deleting the app after creating a backup file. Reinstalling the app did not work either: I hit `install`, F-Droid says it's installing, but nothing happens afterwards.

**Comment by helloworld1** [comment] 2024-02-19 02:25
I wonder if you are able to install the APK from the GitHub. And are there installation issue reported from non pixel phones?

**Comment by gropius365** [comment] 2024-02-19 09:05
Same problem on a Pixel 7 device: upgrade to 3.1.1 from a previously installed (for some time) 3.1 fails wihout error messge.

I did not attempt any uninstalls or reinstalls by other means.

> Funnily, I had 3.1 installed from F-Droid and wasn't able to upgrade to 3.1.1. It's also a Pixel phone. I removed it and tried to install 3.1.1, 3.1 and 3.0 unsuccessfully, so I had to install from Play Store instead.

**Comment by jugendhacker** [comment] 2024-02-20 11:40
> I wonder if you are able to install the APK from the GitHub. And are there installation issue reported from non pixel phones?

Maybe it might also be helpful if someone with a pixel phone could get a adb logcat dump, usually the package installer logs there why the installation/upgrade failed exactly

**Comment by Blurp2222** [comment] 2024-02-26 23:16
No funciona tampoco el actualizado de F-droid y tampoco de los otros aplicaciones.... 


![Screenshot_2024-02-27-00-13-48-29_66a3b1c2c181ff92b8bf945e748b6fb7](https://github.com/helloworld1/FreeOTPPlus/assets/161391222/4a61f985-ed5c-41d6-9ebb-31bd7bbf15aa)

**Comment by vicnett** [comment] 2024-02-26 23:19
I just realized it fixed itself and 3.1.1 is now installed on my Pixel 8.
What's weird though is that I didn't do anything so I'm not sure how it
happened...

**Comment by jugendhacker** [comment] 2024-02-27 06:34
@Blurp2222 your error is probably unrelated as it looks like F-Droid is trying to connect to Tor / Orbit, which does not seem to be running

**Comment by helloworld1** [comment] 2024-02-27 06:50
If any pixel users can grab related adb logcat or adb install log, it will be very helpful to debug the issue further since I don't have a pixel phone to reproduce the problem.

**Comment by Urbi2k** [comment] 2024-02-27 11:28
I tried to update to version 3.1.1 again after reading here that some people where successful. At first it didn't work. Same issue as before. However, half an hour ago I got a F-Droid update so I decided to try installing FreeOTP+ from F-Droid one more time and it worked without any issues. So maybe it was a F-Droid-Problem to begin with?

**Comment by nackd** [comment] 2024-02-27 13:17
See https://gitlab.com/fdroid/fdroidclient/-/issues/2752. I'd guess we can close this one too.

**Comment by helloworld1** [comment] 2024-03-18 04:22
Thanks everyone!

**Closed by helloworld1** 2024-03-18 04:22 UTC
