### ISSUE TITLE
Missing string to translate

### ISSUE THREAD

**Issue by atallo** [helloworld1/FreeOTPPlus#192] opened 2022-03-07 10:24 UTC
String "Token details" appears untranslated. In Crowdin it does not appear to translate.

Thanks

![2022-03-07 at 11 11 53 AM](https://user-images.githubusercontent.com/586093/157012850-e39895c6-104d-4473-976f-451b8fca4de2.jpeg)

**Comment by helloworld1** [comment] 2022-03-27 23:40
Thanks for reporting.  The translations are provided by contributors. Unfortunately I cannot fix on my own. Could you tell me what is the language in question? Thanks!

**Comment by atallo** [comment] 2022-03-31 06:25
I translated most of the strings. But in the list there is no "Token details" in crowdin.

Spanish is my language.  But It is a problem that appears in all translations.

![image](https://user-images.githubusercontent.com/586093/160990032-db179acd-d9c7-4c7d-bed8-9f17e147e74a.png)

**Comment by helloworld1** [comment] 2022-04-11 21:50
@atallo Got it. Thank you. I will change that.

**Comment by helloworld1** [comment] 2022-04-15 05:19
The issue is fixed in https://github.com/helloworld1/FreeOTPPlus/commit/7f07f9107655bf0abbddf54e64ba60c7acba1bd9

**Closed by helloworld1** 2022-04-15 05:19 UTC
