### ISSUE TITLE
[Feature Request] Improve the UI on tablets

### ISSUE THREAD

**Issue by lemmy04** [helloworld1/FreeOTPPlus#121] opened 2021-03-12 07:53 UTC
Please improve the UI on large screens (tablets), the way the original FreeOTP works on those is much better.

On the original FreeOTP i can access 24 tokens per screen without scrolling:
![Inked20210312_084105_LI](https://user-images.githubusercontent.com/664127/110908947-ceab1a00-830f-11eb-9fb6-7b82a1ce0672.jpg)

On FreeOTP+ the same screensize lets me access six tokens:
![Inked20210312_084204-1_LI](https://user-images.githubusercontent.com/664127/110909343-49743500-8310-11eb-87bb-e78b45894eb0.jpg)

Could this be fixed?

**Comment by helloworld1** [comment] 2021-03-22 04:21
I think it is because of moving to RecyclerView. We can consider using a Grid LayoutManger for tablet.

**Comment by helloworld1** [comment] 2021-06-15 05:42
The issue is fixed in https://github.com/helloworld1/FreeOTPPlus/commit/f5a50c92159bb7f97286015aea02c39ab7558133

**Comment by helloworld1** [comment] 2021-06-15 05:43
I don't have a tablet wide enough to test. Feel free to let me know if you can test a debug version (It won't override your current tokens).

**Closed by helloworld1** 2021-06-15 05:42 UTC

**Comment by lemmy04** [comment] 2021-06-15 07:24
sure, i can test... :)

**Comment by helloworld1** [comment] 2021-06-15 22:27
You can download the apk here
https://drive.google.com/file/d/1dCIJ1Xr4FYxsabJhCznUPJenNcfp3xxf/view?usp=sharing

The debug build is a separate app with orange icon. It won't mess up your existing one. Feel free to test functionalities. Note this version has major internal updates. Please create separate issues for other bugs.

**Comment by lemmy04** [comment] 2021-06-16 06:43
tested, the new layout is SO much better.

**Comment by helloworld1** [comment] 2021-06-17 15:04
Thanks for getting back. I will work on the importing sorting problem.
The ordering is currently only on rows (up and down motion). I need to find ways to support left and right motion.

**Comment by helloworld1** [comment] 2021-06-19 03:49
@lemmy04 Could you try a newer APK that should fix the import order and horizontal drag of the tokens.
https://drive.google.com/file/d/1MjCoTqPu-3SVx1h0Q8v2ezV_hu_mbw4T/view?usp=sharing

**Comment by lemmy04** [comment] 2021-08-02 07:46
finally got around to testing that build, works fine.

**Comment by helloworld1** [comment] 2021-08-02 18:47
Thanks for reporting back!

**Comment by lemmy04** [comment] 2021-09-03 09:23
so when will this improved UI be available in a released version...?

**Comment by helloworld1** [comment] 2021-09-05 04:20
I plan to update the release version to F-Droid in the weekend. Thanks for reminding!

**Comment by helloworld1** [comment] 2021-09-06 05:52
The version 2.4 is now released (on Github). Will need to wait a few days for F-droid to pick up.
Google play release will be also a bit later.

**Comment by lemmy04** [comment] 2021-09-13 10:44
so far neither google nor f-droid have picked up the new version. Is that actually normal for how it works with android apps?

**Comment by jugendhacker** [comment] 2021-09-13 11:36
@lemmy04 F-Droid had some trouble automatically picking up the new version, but this is fixed now. It already tried to build the new version [but failed](https://monitor.f-droid.org/builds/log/org.liberty.android.freeotpplus/15)
