### ISSUE TITLE
Adding user image from external storage fails silently

### ISSUE THREAD

**Issue by ss11mik** [helloworld1/FreeOTPPlus#112] opened 2021-02-18 16:20 UTC
When user tries to select an image on SD card as an icon of token, it silently fails.

I guess the app does not have permission to read the external storage and there would be no other use for it, so a Toast with an error would be nice.

**Comment by helloworld1** [comment] 2021-02-18 17:23
Yea, AnyMemo may need to be updated to Android 11 SDK and use the scoped storage. It will, though, severely limit the access to the file system so you won't be able to choose whatever file you want.

**Comment by helloworld1** [comment] 2021-06-15 05:58
The issue is addressed in https://github.com/helloworld1/FreeOTPPlus/commit/72f33089d85148bdb00a63fd39cecdeb0029afd5

**Closed by helloworld1** 2021-06-15 05:58 UTC
